from typing import Any, Protocol


class CatalogRepository(Protocol):
    def get(self) -> list[dict[str, Any]]: ...

    def save(self, catalog: list[dict[str, Any]]) -> None: ...

    def list_providers(self) -> list[str]: ...

    def list_catagories(self) -> list[str]: ...

    def list_subcategories(self, category: str) -> list[str]: ...
